Noisily fail when rotate credentials
While reviewing the current PR we noticed that the rotation of
credentials and certificates is not working as expected.

Some symptoms where that the CF admin user was block, and errors
when accessing some endpoints of CF (see below).

Error when calling `cf curl /v2/organizations/c0f77ba4-5daf-4f3c-a788-dbdd5d7ef372/spaces?order-by=name&inline-relations-depth=1`:

  {"timestamp":1519898481.2078676,"message":"Request failed: 500: {\"error_code\"=>\"UnknownError\", \"description\"=>\"An unknown error occurred.\", \"code\"=>10001, \"test_mode_info\" =>{\"description\"=>\"bad decrypt\", \"error_code\"=>\"CF-CipherError\" …

diff --git a/concourse/pipelines/create-cloudfoundry.yml b/concourse/pipelines/create-cloudfoundry.yml
--- a/concourse/pipelines/create-cloudfoundry.yml
+++ b/concourse/pipelines/create-cloudfoundry.yml
@@ -3000,6 +3000,11 @@ jobs:
             - -e
             - -c
             - |
+              echo "ERROR: We suspect this feature is currently broken. Exiting."
+              echo "You can manually disable this warning, push the pipeline"
+              echo "and rerun if you really require to run this task"
+              exit 1
+
               VAL_FROM_YAML=$(pwd)/paas-cf/concourse/scripts/val_from_yaml.rb
 
               sed "s/^secrets_uaa_admin_password:.*$//" cf-secrets/cf-secrets.yml \
@@ -3116,6 +3121,11 @@ jobs:
             - -e
             - -c
             - |
+              echo "ERROR: We suspect this feature is currently broken. Exiting."
+              echo "You can manually disable this warning, push the pipeline"
+              echo "and rerun if you really require to run this task"
+              exit 1
+
               mkdir certs
               echo "Extracting extant certs"
               tar -xvzf cf-certs/cf-certs.tar.gz -C certs
